//
//  SlideConfiguration.swift
//
//  This file is automatically generated by SlideGen
//

import SwiftUI
import SlideKit

struct SlideConfiguration {

    /// Edit the slide size.
    let size = SlideSize.standard16_9

    ///  Add your slides into the trailing closure.
    let slideIndexController = SlideIndexController {
        IntroductionSlide()
        SampleSlide()
        CustomizedSlide()
    }

    let theme = CustomTheme()
}

struct CustomTheme: SlideTheme {
    let headerSlideStyle = CustomHeaderSlideStyle2()
    let itemStyle = CustomItemStyle()
    let indexStyle = CustomIndexStyle()
}
